支持显示最新构建提交信息
ybw0014/guizhan-builds-2-frontend pull request #16
Opened 2023-08-03 14:14 UTC by StarWishsama

格式由 idea 自动排版，可能需要更改
我不太会前端 :(

2023-08-03 16:28 UTC, ybw0014 requested changes

2023-08-03 16:28 UTC, ybw0014 commented on pages/sf-subscription.vue
>              </div>
这样改会全部显示在一行里，可以考虑改成下面这样
```suggestion
          <div v-if="lastUpdateTime" class="text-gray-500 text-sm flex flex-col gap-2">
            <div class="flex gap-2">
              {{ t("pages.sfSubscription.devCheck.lastUpdate", {time: $dayjs(lastUpdateTime).format("lll")}) }}
              <div v-if="noUpdate">
                {{ t("pages.sfSubscription.devCheck.noUpdate") }}
              </div>
            </div>
            {{ t("pages.sfSubscription.devCheck.updateInfo", {updateInfo: lastUpdateCommit}) }}
```

2023-08-03 16:28 UTC, ybw0014 commented on stores/useCacheStore.ts
> +      lastUpdateLog: ""
`lastUpdateCommit`会不会更好点

2023-08-03 16:28 UTC, ybw0014 commented on pages/sf-subscription.vue
> +            {{ t("pages.sfSubscription.devCheck.updateInfo", {updateInfo: lastUpdateCommit}) }}
`updateInfo`与语言文件内的`changelog`不一致

2023-08-03 16:28 UTC, ybw0014 commented on pages/sf-subscription.vue
> +            {{ t("pages.sfSubscription.devCheck.lastUpdate", {time: $dayjs(lastUpdateTime).format("lll")}) }}
花括号与内容之间要有空格

2023-08-04 11:24 UTC, ybw0014 commented
奇怪，pages的preview build哪去了

2023-08-04 17:37 UTC, ybw0014 requested changes

2023-08-04 17:37 UTC, ybw0014 commented on pages/sf-subscription.vue
> +  cacheStore.setLastUpdateCommit(lastUpdateCommit.value);
存储commit有必要么，存储时间戳就已经可以比较上次下载与当前最新版本的差异了

2023-08-04 17:39 UTC, StarWishsama commented on pages/sf-subscription.vue
> +  cacheStore.setLastUpdateCommit(lastUpdateCommit.value);
缓存的 commit log🤔

2023-08-04 17:42 UTC, ybw0014 commented on pages/sf-subscription.vue
> +  cacheStore.setLastUpdateCommit(lastUpdateCommit.value);
关键你也没从缓存读啊

2023-08-04 17:58 UTC, ybw0014 approved these changes

2023-08-04 17:58 UTC, merged